# Django settings for omm project.
from lingcod.common.default_settings import *

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
APP_NAME = "Washington"

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'washington',
        'USER': 'postgres',
     }
}

GEOMETRY_DB_SRID = 32610 

TIME_ZONE = 'America/Vancouver'
LANGUAGE_CODE = 'en-us'
SITE_ID = 1
USE_I18N = True

#SECRET_KEY = 'keep_the_one_autogenerated_by_django-admin'

ROOT_URLCONF = 'wmm.urls'

TEMPLATE_DIRS = ( os.path.realpath(os.path.join(os.path.dirname(__file__), 'templates').replace('\\','/')), )

INSTALLED_APPS += ( 'lingcod.analysistools', 
                    'scenario')

# Make this unique, and don't share it with anybody.
SECRET_KEY = '3j9~fjio+adjf93iwashingtonjda()#Jfk3ljf-ea9#$@#90dsfj9@0aj3()*fj3iow2f'

PRIVATE_KML_ROOT = '/usr/local/privatekml'
BOOKMARK_FEATURE = True

#GRASS variables
GISBASE = "/usr/local/grass-6.4.1RC2"
GISDBASE = "/mnt/wmm/grass"
GRASS_TMP = "/tmp"
GRASS_PATH = "/usr/local/grass-6.4.1RC2/bin:/usr/local/grass-6.4.1RC2/scripts:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
GRASS_VERSION = "6.4.1"
GRASS_LIB_PATH = "/usr/local/grass-6.4.1RC2/lib"

from settings_local import *
